### ISSUE TITLE
FTP upload

### ISSUE THREAD

**Issue by Leonyan938** [ergusto/ptp#2]
I was wondering if it is possible to add FTP upload feature? The reason is some shared seedbox such as ultraseedbox doesn't have root access and therefore can't install this Automator. But it can be installed in a dedicated server or VPS and then use FTP to upload torrents to the watch folder of the shared seedbox. 

I think it would be awesome if this feature can be added, just like autodl-irssi that grab seed and ftp upload to anywhere you want :)

Just a suggestion.

Thanks a million

**Comment by ergusto** [comment]
Thanks for the suggestion! This certainly could be implemented, but I would suggest trying to get Node installed on your seedbox first - it is possible without root. You can either follow [this](https://hackernoon.com/how-to-install-node-js-on-ubuntu-16-04-18-04-using-nvm-node-version-manager-668a7166b854) guide, which will install Node and NPM via NVM, or create a ticket with Ultraseedbox if that's who your seedbox provider is - I know for sure that they'll be able to help you get NodeJS installed on your seedbox. 

Let me know how that goes. Running the script on your seedbox is definitely preferable, plus will save you money if that's all you need the VPS for.

**Comment by Leonyan938** [comment]
Wow thank you so much for the suggestion. I’ll check if I’m able to follow the guide and work it out. Otherwise I’ll check with ultraseedbox support to see if they can help me with installation or not. I thought root was needed. Good news for me lol 

Thanks a lot

**Comment by ergusto** [comment]
No prob. Will close this for now.
